# Generated by Django 3.2.12 on 2022-03-10 06:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SongInfo',
            fields=[
                ('song', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('album', models.CharField(max_length=200)),
                ('year', models.IntegerField(validators=[django.core.validators.MaxValueValidator(1900), django.core.validators.MaxValueValidator(2022)])),
                ('genre', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='ratings',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
