# Generated by Django 3.2.12 on 2022-03-10 06:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0002_auto_20220310_0618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songinfo',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2022)]),
        ),
    ]
